### ISSUE TITLE
Problem importing orsopy in 3.10

### ISSUE THREAD

**Issue by andyfaff** [reflectivity/orsopy#71] opened 2021-12-28 11:18 UTC
I'm [experiencing a problem](https://github.com/refnx/refnx/runs/4649235289?check_suite_focus=true) importing orsopy on Python==3.10:
```
refnx/dataset/__init__.py:2: in <module>
    from refnx.dataset.reflectdataset import ReflectDataset, OrsoDataset
refnx/dataset/reflectdataset.py:13: in <module>
    from orsopy.fileio import load_orso
/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/orsopy/fileio/__init__.py:4: in <module>
    from .base import (Header, Column, Person, ValueRange, ValueVector, Value,
/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/orsopy/fileio/base.py:389: in <module>
    class Value(Header):
/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/orsopy/fileio/base.py:126: in __new__
    init_fun = _custom_init_fn(flds, False, has_post_init, 'self', globals())
/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/orsopy/fileio/base.py:76: in _custom_init_fn
    line = _field_init(f, frozen, locals, self_name)
E   TypeError: _field_init() missing 1 required positional argument: 'slots'
```

For some reason it's only failing on Linux, not Windows or macOS. @aglavic, you'd be better placed to answer this query.

**Comment by andyfaff** [comment] 2021-12-28 11:25
I last ran this test on ~10/11 Dec, so if there hasn't been changes to an orsopy release, then it's possible that something changed in Python 3.10 since then to start causing issues.

**Comment by andyfaff** [comment] 2021-12-28 11:36
I've just confirmed that this is an issue on a clean conda env of Python3.10 in a Ubuntu VM.

**Comment by bmaranville** [comment] 2021-12-29 04:17
It is happening because of https://github.com/python/cpython/commit/d3062f672c92855b7e9e962ad4bf1a67abd4589b and I don't know if there is a super simple workaround other than try/except a function call with and without the slots argument, as the (private) function interface is changing within the active 3.10 branch.

**Comment by andyfaff** [comment] 2021-12-29 04:22
Is our implementation fragile?

**Comment by aglavic** [comment] 2021-12-30 10:19
We are using dataclasses in a way they are not intended. This therefore requires some low-level modification that use undocumented parts of the API. The only alternative I could see would be to completely use own code for this functionality, which comes at other cost as being less tested.

As `dataclasses` is at least a builtin module the possible issues should only be python version dependent. Considering how I had to fix crashes in GenX for every release of wxPython it seems not to be too hard to check for any new major Python revision and maybe have a few small fixes.

I'll have a look for a fix when I find the time early next year.

**Comment by aglavic** [comment] 2021-12-30 10:40
I can confirm the same issue on Windows. It happens with python 3.10.1 but not 3.10.0 (default 3.10 on anaconda).

**Comment by aglavic** [comment] 2021-12-30 11:01
I'll close this issue, we can continue discussion on the pull request.

**Closed by aglavic** 2021-12-30 11:01 UTC
Labels: bug
